name: Neural Network CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache build dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            build
          key: ${{ runner.os }}-build-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install build tools and linter
        run: sudo apt-get update && sudo apt-get install -y clang-format cppcheck libcunit1-dev

      - name: Check code formatting
        run: |
          find . -name "*.c" -o -name "*.h" | xargs clang-format --dry-run --Werror --style=Google

      - name: Build project
        run: make all

      - name: Run tests
        run: make test

      - name: Run static code analysis
        run: |
          cppcheck --enable=all -I nn/include --suppress=missingIncludeSystem --inconclusive --error-exitcode=1 .